# Generated by Django 4.1.7 on 2023-05-29 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='birthday_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='nomenclature',
            name='created_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='created_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='created_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='requisit_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='provider_requisits',
            name='bank_account',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='provider_requisits',
            name='bank_bik',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='provider_requisits',
            name='bank_cors_account',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='provider_requisits',
            name='created_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='provider_requisits',
            name='inn',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='provider_requisits',
            name='ogrn',
            field=models.IntegerField(null=True),
        ),
    ]
