# Generated by Django 4.1.7 on 2023-02-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('type', models.CharField(max_length=256)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('rec_purchase_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('purchase_quantity', models.DecimalField(decimal_places=2, max_digits=9)),
                ('in_stock_quantity', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
