# Generated by Django 4.1.7 on 2023-05-31 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_contact_created_at_contact_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='requisit_id',
        ),
        migrations.RemoveField(
            model_name='provider_requisits',
            name='bank_city',
        ),
    ]
