# Generated by Django 4.1.7 on 2023-05-31 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_provider_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='created_by',
            field=models.IntegerField(null=True, verbose_name='main_app.User'),
        ),
    ]
