# Generated by Django 4.1.7 on 2023-05-31 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_contact_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='description',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='nomenclature',
            name='name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='nomenclature',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='provider_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='purchase_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='wholesale_price',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='title',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='provider_requisits',
            name='address',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='provider_requisits',
            name='bank_name',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='provider_requisits',
            name='org_type',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='provider_requisits',
            name='provider_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='provider_x_contact',
            name='contact_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='provider_x_contact',
            name='provider_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='provider_x_nomenclature',
            name='nomenclature_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='provider_x_nomenclature',
            name='provider_id',
            field=models.IntegerField(null=True),
        ),
    ]
