# Generated by Django 4.1.7 on 2023-06-02 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_orders_amount_alter_contact_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='birthday_date',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
