# Generated by Django 4.1.7 on 2023-06-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_contact_birthday_date_alter_contact_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='meta_order_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
